# Generated by Django 2.2.19 on 2024-08-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Расходы', 'Расходы'), ('Доходы', 'Доходы')], default='Расходы', max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
